apiVersion: v1
kind: Pod
metadata:
  labels:
    run: staticpod
  name: staticpod
spec:
  containers:
    - image: nginx
      name: staticpod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
